name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
    - run: npm install
    - name: Start the server
    - run: node server/server.js &

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
    - run: npm install
    - name: Start the server
    - run: node server/server.js &
    - name: Execute UI tests
    - run: npm test
